#pragma config(Motor,  port1,           RightBack,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LinearLift,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ArmLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ArmRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           MobileRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           MobileLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LeftBack,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

void LeftDrive (int pwr)
{
	motor[LeftFront]= motor[LeftBack]= pwr;
}
void RightDrive (int pwr)
{
	motor[RightFront]= motor[RightBack]= pwr;
}
void Linear (int pwr)
{
	motor[LinearLift] = pwr;
}
void MobileGoalLift (int pwr)
{
	motor[MobileRight] = motor[MobileLeft] = pwr;
}
void Arm (int pwr)
{
	motor[ArmLeft] = motor[ArmRight] = pwr;
}
void Intaking (int pwr)
{
	motor[Intake] = pwr;
}

void GoRobot(int Lpwr, int Rpwr, int time)
{
	LeftDrive(Lpwr);
	RightDrive(Rpwr);
	wait1Msec(time);
	LeftDrive(0);
	RightDrive(0);
}

void GoMobileGoal (int Mgpwr, int time)
{
	MobileGoalLift (Mgpwr);
	wait1Msec(time);
	MobileGoalLift (0);
}

void GoIntake (int Ipwr, int time)
{
	Intaking (Ipwr);
	wait1Msec(time);
	Intaking (0);
}

void GoArm (int Apwr, int time)
{
	Arm (Apwr);
	wait1Msec(time);
	Arm (0);
}

void GoLinear (int LLpwr, int time)
{
	Linear (LLpwr);
	wait1Msec(time);
	Linear (LLpwr);
}

void Arcade (int move, int rot)
{
	LeftDrive(move+rot);
	RightDrive(move-rot);
}

void Tank (int lPwr, int rPwr)
{
	LeftDrive(lPwr);
	RightDrive(rPwr);
}

void DriveControl1()
{
	Arcade(vexRT[Ch2], vexRT[Ch1]);
	if (vexRT[Btn6U])
		Linear (127);
	else if(vexRT[Btn6D])
		Linear(-127);
	else
		Linear(0);
	if (vexRT[Btn5U])
		Arm (-127);
	else if(vexRT[Btn5D])
		Arm(127);
	else
		Arm(0);
	if (vexRT[Btn7R])
		MobileGoalLift (127);
	else if(vexRT[Btn7L])
		MobileGoalLift(-127);
	else
		MobileGoalLift(0);
	if (vexRT[Btn7U])
		Intaking (127);
	else if(vexRT[Btn7D])
		Intaking(-127);
	else
		Intaking(0);
}
void pre_auton()
{

}

task autonomous()
{
	GoIntake (-127, 500);
	GoArm (-127, 500);
	GoLinear (127, 750);
	GoRobot (127, -127, 725);
	GoRobot (127, 127, 10);
	GoArm (127, 1250);
	GoIntake (-127, 750);
	GoArm (127, 500);
	GoRobot (-127, 127, 400);
	GoRobot (127, 127, 100);
	GoIntake (127, 750);
	GoRobot (-127, -127, 500);
	GoArm (127, 500);
	GoRobot (127, 127, 250);
	GoIntake (-127, 750);
}
task usercontrol()
{
	while(true)
	{
		DriveControl1();
	}
}
