#pragma config(Motor,  port1,           LeftBack,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ClawRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RvDFourBarRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RvDFourBarLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ChainLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           MobileGoal,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ClawLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LeftFront,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

void LeftDrive (int pwr)
{
	motor[LeftFront]= motor[LeftBack]= pwr;
}
void RightDrive (int pwr)
{
	motor[RightFront]= motor[RightBack]= pwr;
}
void ReverseBar (int pwr)
{
	motor[RvDFourBarRight] = motor[RvDFourBarLeft] = pwr;
}
void ChainLifting (int pwr)
{
	motor[ChainLift] = pwr;
}
void Claw(int pwr)
{
	motor[ClawRight] = motor[ClawLeft] = pwr;
}
void MobileGoalLift (int pwr)
{
	motor[MobileGoal] = pwr;
}
void GoRobot(int Lpwr, int Rpwr, int time)
{
	LeftDrive(Lpwr);
	RightDrive(Rpwr);
	wait1Msec(time);
	LeftDrive(0);
	RightDrive(0);
}
void GoDoubleBar (int Dbpwr, int time)
{
	ReverseBar (Dbpwr);
	wait1Msec(time);
  ReverseBar (0);
}
void GoChainLift (int Clpwr, int time)
{
	ChainLifting (Clpwr);
	wait1Msec(time);
	ChainLifting (0);
}
void GoClaw (int Cwpwr, int time)
{
	Claw (Cwpwr);
	wait1Msec(time);
	Claw (0);
}

void GoMobileGoal (int Mgpwr, int time)
{
	MobileGoalLift (Mgpwr);
	wait1Msec(time);
	MobileGoalLift (0);
}

void Arcade (int move, int rot)
{
	LeftDrive(move+rot);
	RightDrive(move-rot);
}
void Tank (int lPwr, int rPwr)
{
	LeftDrive(lPwr);
	RightDrive(rPwr);
}
void DriveControl1()
{
	Arcade(vexRT[Ch1], vexRT[Ch2]);
	if(vexRT[Btn5U] == 1)
	{
		Claw(127);
	}
	else if(vexRT[Btn5D] == 1)
	{
		Claw(-127);
	}
	else
	{
		Claw(0);
	}
	if (vexRT[Btn6U] == 1)
	{
		ChainLifting(127);
	}
	else if(vexRT[Btn6D] == 1)
	{
		ChainLifting(-127);
	}
	else
	{
		ChainLifting(0);
	}
	if (vexRT[Btn7U] == 1)
	{
		ReverseBar(127);
	}
	else if(vexRT[Btn7D] == 1)
	{
		ReverseBar(-127);
	}
	else
	{
		ReverseBar(0);
	}
	if (vexRT[Btn7R] == 1)
	{
		MobileGoalLift(127);
	}
	else if(vexRT[Btn7L] == 1)
	{
		MobileGoalLift(-127);
	}
	else
	{
		MobileGoalLift(0);
	}
}

void pre_auton()
{

}
task autonomous()
{
	GoRobot (127, 127, 2000);
	GoChainLift (-127, 500);
	GoClaw (-127, 250);
	GoRobot (127, -127, 250);
	GoChainLift (-127, 100);
	GoClaw (-127, 250);
	GoChainLift (127, 100);
}
task usercontrol()
{
	while(true)
	{
		DriveControl1();
	}
}
