#pragma config(Sensor, dgtl1,  JumperSwitch,   sensorDigitalIn)
#pragma config(Motor,  port1,           RightFront,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LeftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LinearLift,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           IntakeRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           IntakeLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           IntakeArm,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           GoalRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          GoalLeft,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

void LeftDrive (int pwr) //left side drive
{
	motor[LeftFront]= motor[LeftBack]= pwr;
}
void RightDrive (int pwr) //right side drive
{
	motor[RightFront]= motor[RightBack]= pwr;
}
void Intake (int pwr) //intake movement
{
	motor[IntakeLeft] = motor[IntakeRight] = pwr;
}
void Goal (int pwr) //bottom goal movement
{
	motor[GoalLeft] = motor[GoalRight] = pwr;
}
void Linear (int pwr) //linear lift movement
{
	motor[LinearLift] = pwr;
}
void Arm (int pwr) //arm attached intake movement
{
	motor[IntakeArm] = pwr;
}

void GoRobot(int Lpwr, int Rpwr, int time) //all drive
{
	LeftDrive(Lpwr);
	RightDrive(Rpwr);
	wait1Msec(time);
	LeftDrive(0);
	RightDrive(0);
}

void LinLift (int Linpwr, int time) //moves the linear lift
{
	Linear(Linpwr);
	wait1Msec(time);
	Linear(0);
}

void MoveGoal (int Gpwr, int time) //moves the goal
{
	Goal(Gpwr);
	wait1Msec(time);
	Goal(0);
}

void MoveArm (int Apwr, int time) //moves the arm
{
	Arm(Apwr);
	wait1Msec(time);
	Arm(0);
}

void GoliathIntake (int Ipwr, int time) //moves the intake
{
	Intake(Ipwr);
	wait1Msec(time);
	Intake(0);
}

void leftAuton ()
{
	GoRobot(127, 127, 3000); //robot moves forward
	MoveGoal(127, 500); //goal moves out to collect mobile goal
	MoveGoal(-127, 500); //goal comes back in to take in mobile goal
	GoRobot(-127, 127, 1000); //robot turns around to go back
	GoRobot(127, 127, 3000); //robot goes back to start
	GoRobot(127, -127, 250); //robot turns slightly to be parallel to first line
	MoveGoal(127, 500); //goal moves the mobile goal into the five point zone
	MoveGoal(127, 500); //goal moves back out of the five point zone
}

void rightAuton ()
{
	GoRobot(127, 127, 3000); //robot moves forward
	MoveGoal(127, 500); //goal moves out to collect mobile goal
	MoveGoal(-127, 500); //goal comes back in to take in mobile goal
	GoRobot(127, -127, 1000); //robot turns around to go back
	GoRobot(127, 127, 3000); //robot goes back to start
	GoRobot(-127, 127, 250); //robot turns slightly to be parallel to first line
	MoveGoal(127, 500); //goal moves the mobile goal into the five point zone
	MoveGoal(127, 500); //goal moves back out of the five point zone
}
void Arcade (int move, int rot) // for controller movement set up
{
	LeftDrive(move + rot);
	RightDrive(move - rot);
}

void pre_auton()
{
}

task autonomous()
{
	if (SensorValue[JumperSwitch])
	{
		leftAuton();
	}
	else
	{
		rightAuton();
	}
}

task usercontrol()
{
	while(true)
	{
		Arcade(vexRT[Ch2], vexRT[Ch1]);//move the robot right and left for ch. 1 and forward and backward for ch.2
		if(vexRT[Btn6U] ^ vexRT[Btn6D]) {//moves intake forward and back for button 6 up and down
			if(vexRT[Btn6U])
				Intake(127);
			else
				Intake(-127);
		}
		else
			Intake(0);
	if(vexRT[Btn5U] ^ vexRT[Btn5D]) {//moves the intake arm up and down for button 5 up and down
			if(vexRT[Btn5U])
				Arm(127);
			else
				Arm(-127);
		}
		else
			Arm(0);
	if(vexRT[Btn7U] ^ vexRT[Btn7D]) {//moves the bottom goal forward and back for button 7 up and down
			if(vexRT[Btn7U])
				Goal(127);
			else
				Goal(-127);
		}
		else
			Goal(0);
	if(vexRT[Btn8U] ^ vexRT[Btn8D]) {//moves the linear lift up and down for button 8 up and down
			if(vexRT[Btn8U])
				Linear(127);
			else
				Linear(-127);
		}
		else
			Linear(0);
	}
}
