#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    Potent,         sensorPotentiometer)
#pragma config(Sensor, in2,    light,          sensorReflection)
#pragma config(Sensor, in3,    line,           sensorLineFollower)
#pragma config(Sensor, dgtl1,  butt1,          sensorTouch)
#pragma config(Sensor, dgtl2,  butt2,          sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  us,             sensorSONAR_raw)
#pragma config(Sensor, I2C_1,  enc,            sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  enc2,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int screen = 0;

	int ass1 = false,
		ass2 = false;

	clearLCDLine(0);
	clearLCDLine(1);

	while(true)
	{
		clearLCDLine(0);
		clearLCDLine(1);
		if (screen == 0)
		{
			displayLCDString(0, 1, "Pot: ");
			displayLCDNumber(0, 7, SensorValue[Potent]);
			displayLCDString(1, 1, "Encs: ");
			displayLCDNumber(1, 7, SensorValue[enc]);
			displayLCDChar(1, 11, ',');
			displayLCDNumber(1, 12, SensorValue[enc2]);
			displayLCDNumber(0, 14, screen);
		}
		if (screen == 1)
		{
			displayLCDString(0, 1, "Light: ");
			displayLCDNumber(0, 7, SensorValue[light]);
			displayLCDString(1, 1, "Line: ");
			displayLCDNumber(1, 7, SensorValue[line]);
			displayLCDNumber(0, 14, screen);
		}
		if (screen == 2)
		{
			displayLCDString(0, 1, "Quad: ");
			displayLCDNumber(0, 7, SensorValue[quad]);
			displayLCDString(1, 1, "Ultra: ");
			displayLCDNumber(1, 7, SensorValue[us]);
			displayLCDNumber(0, 14, screen);
		}

		if (SensorValue[butt1] && !ass1)
			screen = screen - 1;
		else if (SensorValue[butt2] && !ass2)
			screen = screen + 1;
		if (screen < 0)
			screen = 2;
		else if (screen > 2)
			screen = 0;


		ass1 = SensorValue[butt1];
		ass2 = SensorValue[butt2];

		wait1Msec(20);
	}
}
